from sys import argv

script,org1,org2,org3,peer0,peer1,peer2,peer3,peer4,peer5 = argv
filename = "../docker-compose-cli.yaml"
target = open(filename,'w')


target.write("# Copyright IBM Corp. All Rights Reserved.\n")
target.write("#\n")
target.write("# SPDX-License-Identifier: Apache-2.0\n")
target.write("#\n\n")

target.write("version: '2'\n\n")

target.write("services:\n\n")

target.write("  orderer.example.com:\n")
target.write("    extends:\n")
target.write("      file:   base/docker-compose-base.yaml\n")
target.write("      service: orderer.example.com\n")
target.write("    container_name: orderer.example.com\n\n")

target.write("  ")
target.write(peer0)
target.write(".")
target.write(org1)
target.write(".example.com:\n")
target.write("    container_name: ")
target.write(peer0)
target.write(".")
target.write(org1)
target.write(".example.com:\n")
target.write("    extends:\n")
target.write("      file:  base/docker-compose-base.yaml\n")
target.write("      service: ")
target.write(peer0)
target.write(".")
target.write(org1)
target.write(".example.com:\n\n")

target.write("  ")
target.write(peer1)
target.write(".")
target.write(org1)
target.write(".example.com:\n")
target.write("    container_name: ")
target.write(peer1)
target.write(".")
target.write(org1)
target.write(".example.com:\n")
target.write("    extends:\n")
target.write("      file:  base/docker-compose-base.yaml\n")
target.write("      service: ")
target.write(peer1)
target.write(".")
target.write(org1)
target.write(".example.com:\n\n")

target.write("  ")
target.write(peer2)
target.write(".")
target.write(org2)
target.write(".example.com:\n")
target.write("    container_name: ")
target.write(peer2)
target.write(".")
target.write(org2)
target.write(".example.com:\n")
target.write("    extends:\n")
target.write("      file:  base/docker-compose-base.yaml\n")
target.write("      service: ")
target.write(peer2)
target.write(".")
target.write(org2)
target.write(".example.com:\n\n")

target.write("  ")
target.write(peer3)
target.write(".")
target.write(org2)
target.write(".example.com:\n")
target.write("    container_name: ")
target.write(peer3)
target.write(".")
target.write(org2)
target.write(".example.com:\n")
target.write("    extends:\n")
target.write("      file:  base/docker-compose-base.yaml\n")
target.write("      service: ")
target.write(peer3)
target.write(".")
target.write(org2)
target.write(".example.com:\n\n")

target.write("  ")
target.write(peer4)
target.write(".")
target.write(org3)
target.write(".example.com:\n")
target.write("    container_name: ")
target.write(peer4)
target.write(".")
target.write(org3)
target.write(".example.com:\n")
target.write("    extends:\n")
target.write("      file:  base/docker-compose-base.yaml\n")
target.write("      service: ")
target.write(peer4)
target.write(".")
target.write(org3)
target.write(".example.com:\n\n")

target.write("  ")
target.write(peer5)
target.write(".")
target.write(org3)
target.write(".example.com:\n")
target.write("    container_name: ")
target.write(peer5)
target.write(".")
target.write(org3)
target.write(".example.com:\n")
target.write("    extends:\n")
target.write("      file:  base/docker-compose-base.yaml\n")
target.write("      service: ")
target.write(peer5)
target.write(".")
target.write(org3)
target.write(".example.com:\n\n")


target.write("  cli:\n")
target.write("    container_name: cli\n")
target.write("    image: hyperledger/fabric-tools\n")
target.write("    tty: true\n")
target.write("    environment:\n")
target.write("      - GOPATH=/opt/gopath\n")
target.write("      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock\n")
target.write("      - CORE_LOGGING_LEVEL=DEBUG\n")
target.write("      - CORE_PEER_ID=cli\n")
target.write("      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051\n")
target.write("      - CORE_PEER_LOCALMSPID=Org1MSP\n")
target.write("      - CORE_PEER_TLS_ENABLED=true\n")
target.write("      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt\n")
target.write("      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key\n")
target.write("      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt\n")
target.write("      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp\n")
target.write("    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer\n")
target.write("    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'\n")
target.write("    volumes:\n")
target.write("        - /var/run/:/host/var/run/\n")
target.write("        - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go\n")
target.write("        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/\n")
target.write("        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/\n")
target.write("        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts\n")
target.write("    depends_on:\n")
target.write("      - orderer.example.com\n")
target.write("      - ")
target.write(peer0)
target.write(".")
target.write(org1)
target.write(".example.com:\n")
target.write("      - ")
target.write(peer1)
target.write(".")
target.write(org1)
target.write(".example.com:\n")
target.write("      - ")
target.write(peer2)
target.write(".")
target.write(org2)
target.write(".example.com:\n")
target.write("      - ")
target.write(peer3)
target.write(".")
target.write(org2)
target.write(".example.com:\n")
target.write("      - ")
target.write(peer4)
target.write(".")
target.write(org3)
target.write(".example.com:\n")
target.write("      - ")
target.write(peer5)
target.write(".")
target.write(org3)
target.write(".example.com:\n")

