from sys import argv

script,org1,org2,org3 = argv
filename = "../crypto-config.yaml"
target = open(filename,'w')

target.write("# Copyright IBM Corp. All Rights Reserved.\n")
target.write("#\n")
target.write("# SPDX-License-Identifier: Apache-2.0\n")
target.write("#\n\n")
target.write("# ---------------------------------------------------------------------------\n")
target.write("# OrdererOrgs - Definition of organizations managing orderer nodes\n")
target.write("# ---------------------------------------------------------------------------\n")
target.write("OrdererOrgs:\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  # Orderer\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  - Name: Orderer\n")
target.write("    Domain: example.com\n")
target.write("    # ---------------------------------------------------------------------------\n")
target.write("    # Specs - See PeerOrgs below for complete description\n")
target.write("    # ---------------------------------------------------------------------------\n")
target.write("    Specs:\n")
target.write("      - Hostname: orderer\n")
target.write("# ---------------------------------------------------------------------------\n")
target.write("# PeerOrgs - Definition of organizations managing peer nodes\n")
target.write("# ---------------------------------------------------------------------------\n")
target.write("PeerOrgs:\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  # Org1\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  - Name: ")
target.write(org1)
target.write("\n")
target.write("    Domain: ")
target.write(org1)
target.write(".example.com\n")
target.write("    Template:\n")
target.write("      Count: 2\n")
target.write("    Users:\n")
target.write("      Count: 1\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  # Org2\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  - Name: ")
target.write(org2)
target.write("\n")
target.write("    Domain: ")
target.write(org2)
target.write(".example.com\n")
target.write("    Template:\n")
target.write("      Count: 2\n")
target.write("    Users:\n")
target.write("      Count: 1\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  # Org3\n")
target.write("  # ---------------------------------------------------------------------------\n")
target.write("  - Name: ")
target.write(org3)
target.write("\n")
target.write("    Domain: ")
target.write(org3)
target.write(".example.com\n")
target.write("    Template:\n")
target.write("      Count: 2\n")
target.write("    Users:\n")
target.write("      Count: 1\n")